FROM ringcentral/node:12.18.2-jdk8u202
LABEL maintainer="john.lin@ringcentral.com"

RUN apk add --no-cache python2 alpine-sdk gradle

#==============
# Show version
#==============
RUN python --version