sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/webtests-runner
  - secure: EKApmXhZE8F2tr4wROslHYHSd9ZNfjFTU/DoNX9WEh8CK7jvZwOxvcQgDmb9Gq7k0gwjgaRJWTyOsXCYN/MDCZqr2btI9Xy6Un8s4zluc4m8W3tNSUfWL6GGSxK5F8uJfjO3XXN8GQToi7b5/pVu/IYdbNK6ms4QXiaAlkwU5ZgRT+u5wgOYbp3F7xJqupUtVrSaCr1FnsqmaYLDaZv2mNmArEBqu/ZoJCxrnoX+DvTSDG2f2Y4bJiRevOVaHJXZ+Oo7oMnlIcB1bBiOSo4r5G3ck5jUMTGNG6pqAn9PG6cAPNCkhx1lMX2qwrzUszEVJj9D1Imn9uuiVkhZQPwEvIdxCSxJEkGrh8DKTQ5/Ht+Gk9V2BV5gXuaB8V7HDHktddvzHjbAHQ7DRTFhXfPNiyBgfVm2BzKinqav2sKVmuO7OGIwKaLS5E14UFgduqK4xkFRPtadxW/qTok6YnLqwo39E/Yr7wjt+F52i0QZzzoFLPE9rdXDf4yQfw6GRd8iC/O3vWKDg+wZl10u7VLbfWjQZdbN+ZHveX9GFuw+axhBjXudUqZNezjse7m2sYR9p4KwDE9Etzv3spLpZtiTSC9G/iXZQ9EMzSR2x1ay6idAyzozyforJ3E/j19jy3373KUdjC8MRvY/3vqbyklGEnO1nFIKHf404MCuOw6N+yM=
  - secure: Oy6oSZ3DdlBICH9BfzRiDroc7U+hqzf4kK0Elj/TZ3MB5hnn8dM2HPioa53S5MB64pvXIoG3kEa2dsKZgXR9EizlsBynVGBQWY0bg1jbvVh52qpXD8EaISUiLgn0SRVwRTWSR2mmS+p746apSzNfdwTVipPTd5ouLRtj+2PFMRrj0ufkODX27W0mwd5zGhd3+gWqU8nbTNGV3veuPlOr/t6/2CT3OFAFVYIjyCZA3wdYcv6A6K/eCFrUDYxGFevQqmzCZ/JD7kCwhR00lyib3gAN++uJ4EePS6Kgfz874f2kg8d/my4eIdXFKpDqDpRwTT2xktsdzHs4XiXXLw1j1ZpMvyREVDcP8IUdrSQzjzTn0UmfeUDY9D+uuw+P1t0DQEsfyFlpTZ7RluhT++CFWCmzlPKPGjk2IkYbtgDR23xCgL4sjCHRknbBBxt/qfwF9c2QEJd+nJgjJUNREnfhixDoUy/VzT1Tw0EfVo2HkC3AA3zIxPllsE6/p/vUcPfKDc76T9NC6UdPkh8K4+9Oaf9nhjA5mEwge3TjVHKftyM9MtnV/HmVM82ggdqZznJ3d8gA35FWWG1fSmbn6L0lTx9iJlpmXORHIBB2TNTq/MDpBANbA7yOSQnS6yLL+oJq8djv7lRhG+YgB226L+mJ26THirilCHkQoWpkxj1VCtE=
before_script:
- cd jdk8
- version="$(awk -F '[:-]' '/FROM/ {print $3}' Dockerfile)"
script:
- docker build -t "$IMAGE_NAME" .
after_script:
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
