FROM ringcentral/node:14.17.6-jdk8u202
LABEL maintainer="john.lin@ringcentral.com"

RUN apk add --no-cache python3 alpine-sdk gradle

#==============
# Show version
#==============
RUN python3 --version