FROM ringcentral/node:20.12.1-jdk11.0.22
LABEL maintainer="john.lin@ringcentral.com"

RUN apk add --no-cache python3 alpine-sdk gradle

#==============
# Show version
#==============
RUN python3 --version