FROM ringcentral/node:14.21.2-jdk17.0.3
LABEL maintainer="john.lin@ringcentral.com"

RUN apk add --no-cache python3 alpine-sdk gradle

#==============
# Show version
#==============
RUN python3 --version