FROM ringcentral/node:10.21.0-jdk8u202
LABEL maintainer="john.lin@ringcentral.com"

RUN apk add --no-cache python2 alpine-sdk gradle

#==============
# Show version
#==============
RUN python --version