name: Build webtests runner base on Node 12

on:
  push:
    branches:
      - master
    paths:
      # '*' matches any character except '/'
      - '12/*'
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker login
      env:
        USER_NAME: ${{ secrets.USER_NAME }}  
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        echo $PASSWORD | docker login --username $USER_NAME --password-stdin

    - name: Build & Push Docker Image
      run: |
        cd 12
        IMAGE_NAME=ringcentral/webtests-runner
        NODE_VERSION="$(awk '/ENV NODE_VERSION/ {print $3}' Dockerfile)"
        NODE_MAJOR_VERSION="$(awk -F '[ .]' '/ENV NODE_VERSION/ {print $3}' Dockerfile)"
        docker build --tag ${IMAGE_NAME} --file Dockerfile .
        docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"
        docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${NODE_MAJOR_VERSION}"
        docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${NODE_VERSION}"
        docker push "${IMAGE_NAME}:${NODE_VERSION}"
        docker push "${IMAGE_NAME}:${NODE_MAJOR_VERSION}"
        docker push "${IMAGE_NAME}:latest"