name: Build WebTest Runner Images

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - 'version.env'
      - '.github/workflows/build-runner.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk_version: [8, 11, 17, 21]
        node_version: [18, 20, 22]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Docker login
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
        echo $GITHUB_TOKEN | docker login ghcr.io --username $GITHUB_ACTOR --password-stdin

    - name: Set Environment Variables
      id: vars
      run: |
        NODE_MAJOR_VERSION=${{ matrix.node_version }}
        JDK_MAJOR_VERSION=${{ matrix.jdk_version }}
        BASE_VERSION="$(awk -F '[=]' '/NODE_${{ matrix.node_version }}_JDK_${{ matrix.jdk_version }}_VERSION/ {print $2}' version.env)"
        NODE_VERSION=${BASE_VERSION%%-*}
        JDK_VERSION=${BASE_VERSION##*-}
        echo "NODE_MAJOR_VERSION=${NODE_MAJOR_VERSION}" >> $GITHUB_ENV
        echo "JDK_MAJOR_VERSION=${JDK_MAJOR_VERSION}" >> $GITHUB_ENV
        echo "BASE_VERSION=${BASE_VERSION}" >> $GITHUB_ENV
        echo "NODE_VERSION=${NODE_VERSION}" >> $GITHUB_ENV
        echo "JDK_VERSION=${JDK_VERSION}" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        IMAGE_NAME=ringcentral/webtests-runner
        sed -i "s/\$VERSION/$BASE_VERSION/g" Dockerfile
        docker build --tag ${IMAGE_NAME} --file Dockerfile .

    - name: Tag and Push Docker Images
      run: |
        IMAGE_NAME=ringcentral/webtests-runner
        GH_DOCKER_PKG_IMAGE_NAME=ghcr.io/ringcentral-docker/webtests-runner/webtests-runner
        
        docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${BASE_VERSION}"
        docker push "${IMAGE_NAME}:${BASE_VERSION}"
        docker tag "${IMAGE_NAME}" "${GH_DOCKER_PKG_IMAGE_NAME}:${BASE_VERSION}"
        docker push "${GH_DOCKER_PKG_IMAGE_NAME}${BASE_VERSION}"

        if [ "${{ matrix.jdk_version }}" -eq 17 ]; then
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${NODE_VERSION}"
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${NODE_MAJOR_VERSION}"
          docker push "${IMAGE_NAME}:${NODE_VERSION}"
          docker push "${IMAGE_NAME}:${NODE_MAJOR_VERSION}"

          docker tag "${IMAGE_NAME}" "${GH_DOCKER_PKG_IMAGE_NAME}:${NODE_VERSION}"
          docker tag "${IMAGE_NAME}" "${GH_DOCKER_PKG_IMAGE_NAME}:${NODE_MAJOR_VERSION}"
          docker push "${GH_DOCKER_PKG_IMAGE_NAME}:${NODE_VERSION}"
          docker push "${GH_DOCKER_PKG_IMAGE_NAME}:${NODE_MAJOR_VERSION}"
          if [ "${{ matrix.node_version }}" -eq 22 ]; then
            docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"
            docker push "${IMAGE_NAME}:latest"
            docker tag "${IMAGE_NAME}" "${GH_DOCKER_PKG_IMAGE_NAME}:latest"
            docker push "${GH_DOCKER_PKG_IMAGE_NAME}:latest"
          fi
        fi

    - name: Generate README Update
      run: |
        IMAGE_NAME=ringcentral/webtests-runner
        GH_DOCKER_PKG_IMAGE_NAME=ghcr.io/ringcentral-docker/webtests-runner/webtests-runner

        NEW_ENTRY="| JDK${{ matrix.jdk_version }} | ${{ matrix.node_version }} | \`${IMAGE_NAME}:${NODE_VERSION}\` \`${IMAGE_NAME}:${NODE_MAJOR_VERSION}\` \`${IMAGE_NAME}:${BASE_VERSION}\` | \`${GH_DOCKER_PKG_IMAGE_NAME}:${NODE_VERSION}\` \`${GH_DOCKER_PKG_IMAGE_NAME}:${NODE_MAJOR_VERSION}\` \`${GH_DOCKER_PKG_IMAGE_NAME}:${BASE_VERSION}\` |"
        echo "${NEW_ENTRY}" > readme-updates-${{ matrix.node_version }}-${{ matrix.jdk_version }}.txt

    - name: Upload README Update
      uses: actions/upload-artifact@v4
      with:
        name: readme-updates-${{ matrix.node_version }}-${{ matrix.jdk_version }}
        path: readme-updates-${{ matrix.node_version }}-${{ matrix.jdk_version }}.txt

  update-readme:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download README Updates
      uses: actions/download-artifact@v4
      with:
        name: readme-updates-18-17
        path: ./readme-updates
    - name: Download README Updates
      uses: actions/download-artifact@v4
      with:
        name: readme-updates-20-17
        path: ./readme-updates
    - name: Download README Updates
      uses: actions/download-artifact@v4
      with:
        name: readme-updates-22-17
        path: ./readme-updates

    - name: Initialize README
      run: |
        echo "| JDK Version | Node Version | Docker Hub | GitHub Package |" > README.md
        echo "|-------------|--------------|------------|----------------|" >> README.md
    - name: Update README
      run: |
        for file in ./readme-updates/readme-updates-*.txt; do
          while IFS= read -r line; do
            JDK_VERSION=$(echo $line | cut -d' ' -f2)
            if grep -q "JDK${JDK_VERSION}" README.md; then
              sed -i "/JDK${JDK_VERSION}/c\\$line" README.md
            else
              echo "$line" >> README.md
            fi
          done < "$file"
        done

    - name: Commit README Update
      run: |
        git config --global user.name 'john.lin'
        git config --global user.email 'john.lin@ringcentral.com'
        git add README.md
        git commit -m "Update README with Docker image info"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}