name: Build WebTest Runner Images

on:
  push:
    branches:
      - master
    paths:
      - '*-jdk*/*'
      - '.github/workflows/build-runner.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk_version: [11, 17, 21]
        node_version: [20]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Docker login
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
        echo $GITHUB_TOKEN | docker login docker.pkg.github.com --username $GITHUB_ACTOR --password-stdin

    - name: Set Environment Variables
      id: vars
      run: |
        NODE_DIR=${{ matrix.node_version }}-jdk${{ matrix.jdk_version }}
        if [[ -f ${NODE_DIR}/Dockerfile ]]; then
          NODE_VERSION="$(awk -F '[:.]' '/FROM/ {print $3}' ${NODE_DIR}/Dockerfile)"
          NODE_MAJOR_VERSION="$(awk -F '[:-]' '/FROM/ {print $3}' ${NODE_DIR}/Dockerfile)"
          BASE_VERSION="$(awk -F '[:]' '/FROM/ {print $2}' ${NODE_DIR}/Dockerfile)"
          echo $NODE_MAJOR_VERSION > ${NODE_DIR}/version.txt
          echo $BASE_VERSION > ${NODE_DIR}/detail_version.txt
        else
          NODE_MAJOR_VERSION=$(cat ${NODE_DIR}/version.txt)
          BASE_VERSION=$(cat ${NODE_DIR}/detail_version.txt)
        fi
        echo "NODE_DIR=${NODE_DIR}" >> $GITHUB_ENV
        echo "NODE_VERSION=${NODE_VERSION}" >> $GITHUB_ENV
        echo "NODE_MAJOR_VERSION=${NODE_MAJOR_VERSION}" >> $GITHUB_ENV
        echo "BASE_VERSION=${BASE_VERSION}" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        IMAGE_NAME=ringcentral/webtests-runner
        docker build --tag ${IMAGE_NAME} --file ${NODE_DIR}/Dockerfile .

    - name: Tag and Push Docker Images
      run: |
        IMAGE_NAME=ringcentral/webtests-runner
        GH_DOCKER_PKG_IMAGE_NAME=docker.pkg.github.com/ringcentral-docker/webtests-runner/webtests-runner

        docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${NODE_MAJOR_VERSION}"
        docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${NODE_VERSION}"
        docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${BASE_VERSION}"
        
        docker push "${IMAGE_NAME}:${NODE_MAJOR_VERSION}"
        docker push "${IMAGE_NAME}:${NODE_VERSION}"
        docker push "${IMAGE_NAME}:${BASE_VERSION}"      

        docker tag "${IMAGE_NAME}" "${GH_DOCKER_PKG_IMAGE_NAME}:${NODE_MAJOR_VERSION}"
        docker tag "${IMAGE_NAME}" "${GH_DOCKER_PKG_IMAGE_NAME}:${NODE_VERSION}"
        docker tag "${IMAGE_NAME}" "${GH_DOCKER_PKG_IMAGE_NAME}:${BASE_VERSION}"
        
        docker push "${GH_DOCKER_PKG_IMAGE_NAME}:${NODE_MAJOR_VERSION}"
        docker push "${GH_DOCKER_PKG_IMAGE_NAME}:${NODE_VERSION}"
        docker push "${GH_DOCKER_PKG_IMAGE_NAME}:${BASE_VERSION}"

        if [ "${{ matrix.jdk_version }}" -eq 21 ]; then
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"
          docker push "${IMAGE_NAME}:latest"
          docker tag "${IMAGE_NAME}" "${GH_DOCKER_PKG_IMAGE_NAME}:latest"
          docker push "${GH_DOCKER_PKG_IMAGE_NAME}:latest"
        fi

    - name: Generate README Update
      run: |
        IMAGE_NAME=ringcentral/webtests-runner
        GH_DOCKER_PKG_IMAGE_NAME=docker.pkg.github.com/ringcentral-docker/webtests-runner/webtests-runner

        NEW_ENTRY="| JDK${{ matrix.jdk_version }} | ${BASE_VERSION} | \`${IMAGE_NAME}:${BASE_VERSION}\` | \`${GH_DOCKER_PKG_IMAGE_NAME}:${BASE_VERSION}\` |"
        echo "${NEW_ENTRY}" > readme_updates_${{ matrix.jdk_version }}.txt

    - name: Upload README Update
      uses: actions/upload-artifact@v4
      with:
        name: readme-updates-${{ matrix.jdk_version }}
        path: readme_updates_${{ matrix.jdk_version }}.txt

  update-readme:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download README Updates
      uses: actions/download-artifact@v4
      with:
        name: readme-updates-8
        path: ./readme-updates
    - name: Download README Updates
      uses: actions/download-artifact@v4
      with:
        name: readme-updates-11
        path: ./readme-updates
    - name: Download README Updates
      uses: actions/download-artifact@v4
      with:
        name: readme-updates-17
        path: ./readme-updates
    - name: Download README Updates
      uses: actions/download-artifact@v4
      with:
        name: readme-updates-21
        path: ./readme-updates

    - name: Initialize README
      run: |
        echo "| JDK Version | Version | Docker Hub | GitHub Package |" > README.md
        echo "|-------------|---------|------------|----------------|" >> README.md
    - name: Update README
      run: |
        for file in ./readme-updates/readme_updates_*.txt; do
          while IFS= read -r line; do
            JDK_VERSION=$(echo $line | cut -d' ' -f2)
            if grep -q "JDK${JDK_VERSION}" README.md; then
              sed -i "/JDK${JDK_VERSION}/c\\$line" README.md
            else
              echo "$line" >> README.md
            fi
          done < "$file"
        done

    - name: Commit README Update
      run: |
        git config --global user.name 'john.lin'
        git config --global user.email 'john.lin@ringcentral.com'
        git add README.md
        git commit -m "Update README with Docker image info"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}